In [6]:
import pandas as pd
att = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/attention.csv")
att.drop(columns=["Unnamed: 0"], inplace=True)
att

    subject attention  solutions  score
0         1   divided          1    2.0
1         2   divided          1    3.0
2         3   divided          1    3.0
3         4   divided          1    5.0
4         5   divided          1    4.0
5         6   divided          1    5.0
6         7   divided          1    5.0
7         8   divided          1    5.0
8         9   divided          1    2.0
9        10   divided          1    6.0
10       11   focused          1    6.0
11       12   focused          1    8.0
12       13   focused          1    6.0
13       14   focused          1    8.0
14       15   focused          1    8.0
15       16   focused          1    6.0
16       17   focused          1    7.0
17       18   focused          1    7.0
18       19   focused          1    5.0
19       20   focused          1    6.0
20        1   divided          2    4.0
21        2   divided          2    4.0
22        3   divided          2    5.0
23        4   divided          2    7.0
24        5   divided          2    5.0
25        6   divided          2    5.0
26        7   divided          2    4.5
27        8   divided          2    7.0
28        9   divided          2    3.0
29       10   divided          2    5.0
30       11   focused          2    5.0
31       12   focused          2    9.0
32       13   focused          2    5.0
33       14   focused          2    8.0
34       15   focused          2    8.0
35       16   focused          2    8.0
36       17   focused          2    7.0
37       18   focused          2    8.0
38       19   focused          2    6.0
39       20   focused          2    6.0
40        1   divided          3    7.0
41        2   divided          3    5.0
42        3   divided          3    6.0
43        4   divided          3    5.0
44        5   divided          3    8.0
45        6   divided          3    6.0
46        7   divided          3    6.0
47        8   divided          3    8.0
48        9   divided          3    7.0
49       10   divided          3    6.0
50       11   focused          3    6.0
51       12   focused          3    8.0
52       13   focused          3    9.0
53       14   focused          3    7.0
54       15   focused          3    7.0
55       16   focused          3    7.0
56       17   focused          3    6.0
57       18   focused          3    6.0
58       19   focused          3    6.0
59       20   focused          3    5.0

In [17]:
att_focus = att[att["attention"] == "focused"].pivot_table(index="subject", columns=["solutions"], values=["score"])

In [22]:
att_div = att[att["attention"] == "divided"].pivot_table(index="subject", columns=["solutions"], values=["score"])

In [10]:
att.pivot_table(index="subject", columns=["solutions"], values=["score"])

          score
solutions     1    2    3
subject
1           2.0  4.0  7.0
2           3.0  4.0  5.0
3           3.0  5.0  6.0
4           5.0  7.0  5.0
5           4.0  5.0  8.0
6           5.0  5.0  6.0
7           5.0  4.5  6.0
8           5.0  7.0  8.0
9           2.0  3.0  7.0
10          6.0  5.0  6.0
11          6.0  5.0  6.0
12          8.0  9.0  8.0
13          6.0  5.0  9.0
14          8.0  8.0  7.0
15          8.0  8.0  7.0
16          6.0  8.0  7.0
17          7.0  7.0  6.0
18          7.0  8.0  6.0
19          5.0  6.0  6.0
20          6.0  6.0  5.0

In [24]:
focus_avg = att[att["attention"] == "focused"]["score"].mean()

In [26]:
div_avg = att[att["attention"] == "divided"]["score"].mean()

In [28]:
focus_avg / div_avg

1.3289902280130295

In [44]:
solution_avgs = {
      1 : att[att["solutions"] == 1]["score"].mean(),
      2 : att[att["solutions"] == 2]["score"].mean(),
      3 : att[att["solutions"] == 3]["score"].mean()
    }

max(solution_avgs, key=solution_avgs.get)

3

In [64]:
sub_avgs = pd.DataFrame(att.groupby(["subject"])["score"].mean())

In [79]:
sub_avgs = sub_avgs.sort_values(by=["score", "subject"], ascending=[False, True])[:10].reset_index()

In [80]:
sub_avgs

   subject     score
0       12  8.333333
1       14  7.666667
2       15  7.666667
3       16  7.000000
4       18  7.000000
5        8  6.666667
6       13  6.666667
7       17  6.666667
8        4  5.666667
9        5  5.666667